#PBS -N Gene_RBMs
#PBS -l nodes=1:ppn=20
#PBS -l mem=20gb
#PBS -l walltime=5:00:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/03b_geneRBMs_${n}.out
#PBS -e 00a_log/03b_geneRBMs_${n}.err

## Runs all verse all aai.rb in nucleotide mode on directory of genomes
## Uses gnu parallel to speed it up
## enveomics aai.rb must be installed in the user path
## blast+ must be installed in the user path

module load parallel/20190222

cd $PBS_O_WORKDIR

if [ ! -d ${fDir}/${oDir} ]; then mkdir ${fDir}/${oDir}; fi

# run fastANI in parallel
parallel -j 20 --joblog 00a_log/03b_parallel_${n}.log 'aai.rb -1 {1} -2 {2} -N -R {3}/{1/.}-{2/.}.rbm -o {3}/{1/.}-{2/.}.out -r {3}/{1/.}-{2/.}.res -T {3}/{1/.}-{2/.}.tsv' ::: ${fDir}/01_FNN/*fnn ::: ${fDir}/01_FNN/*fnn ::: "${fDir}/${oDir}"

# clean up temp gList
rm ${gList}

## Run log:
## qsub -v fDir=Genome_Directory,oDir=Output_Directory,n=Species_name ../../00b_PBS/03b_Gene_RBMs.pbs
## for d in Complete/*; do n=`basename $d`; qsub -v fDir=$d,oDir=04_RBM,n=$n ../../00b_PBS/03b_Gene_RBMs.pbs; done
