#PBS -N delete
#PBS -l nodes=1:ppn=1
#PBS -l mem=1gb
#PBS -l walltime=24:00:00
#PBS -q inferno     
#PBS -A GT-ktk3-CODA20
#PBS -o 00a_log/delete_${name}_${ext}.out
#PBS -e 00a_log/delete_${name}_${ext}.err

cd $PBS_O_WORKDIR

path="/storage/home/hcoda1/9/rconrad6/p-ktk3-0/04_Recombination/01b_Genomes/bacteria/Complete/${name}/04_RBM"

for f in ${path}/*.${ext}; do rm $f; done

## Run Log
## qsub -v name=,ext= 00b_PBS/removeEcoliA.pbs
